// Generated by scripts/promote-landmarks.mjs. Do not edit by hand.
import type { Destination } from './index'

export const LANDMARK_SCENES_SHIPPING_ELIGIBLE = false as const

export const LANDMARK_DESTINATIONS = [
  {
    "id": "china-beijing-forbidden-city-corner-tower",
    "name": "故宫角楼",
    "sceneVariants": [
      {
        "id": "china-beijing-forbidden-city-corner-tower--day-signature",
        "destinationId": "china-beijing-forbidden-city-corner-tower",
        "imageSrc": "/scenes/scene--china-beijing-forbidden-city-corner-tower--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.79,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-beijing-forbidden-city-corner-tower--golden-hour",
        "destinationId": "china-beijing-forbidden-city-corner-tower",
        "imageSrc": "/scenes/scene--china-beijing-forbidden-city-corner-tower--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.91,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "japan-kyoto-fushimi-inari-taisha",
    "name": "京都伏见稻荷",
    "sceneVariants": [
      {
        "id": "japan-kyoto-fushimi-inari-taisha--day-signature",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/scenes/scene--japan-kyoto-fushimi-inari-taisha--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "japan-kyoto-fushimi-inari-taisha--golden-hour",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/scenes/scene--japan-kyoto-fushimi-inari-taisha--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.805,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "japan-kyoto-fushimi-inari-taisha--companion-rare",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/scenes/scene--japan-kyoto-fushimi-inari-taisha--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "singapore-singapore-merlion",
    "name": "新加坡鱼尾狮",
    "sceneVariants": [
      {
        "id": "singapore-singapore-merlion--day-signature",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/scenes/scene--singapore-singapore-merlion--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "singapore-singapore-merlion--golden-hour",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/scenes/scene--singapore-singapore-merlion--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "singapore-singapore-merlion--companion-rare",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/scenes/scene--singapore-singapore-merlion--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "australia-sydney-opera-house",
    "name": "悉尼歌剧院",
    "sceneVariants": [
      {
        "id": "australia-sydney-opera-house--day-signature",
        "destinationId": "australia-sydney-opera-house",
        "imageSrc": "/scenes/scene--australia-sydney-opera-house--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.89,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "australia-sydney-opera-house--golden-hour",
        "destinationId": "australia-sydney-opera-house",
        "imageSrc": "/scenes/scene--australia-sydney-opera-house--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.89,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "australia-sydney-opera-house--companion-rare",
        "destinationId": "australia-sydney-opera-house",
        "imageSrc": "/scenes/scene--australia-sydney-opera-house--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.89,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "france-paris-eiffel-tower",
    "name": "巴黎埃菲尔铁塔",
    "sceneVariants": [
      {
        "id": "france-paris-eiffel-tower--day-signature",
        "destinationId": "france-paris-eiffel-tower",
        "imageSrc": "/scenes/scene--france-paris-eiffel-tower--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.89,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "france-paris-eiffel-tower--golden-hour",
        "destinationId": "france-paris-eiffel-tower",
        "imageSrc": "/scenes/scene--france-paris-eiffel-tower--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.89,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "united-kingdom-london-tower-bridge",
    "name": "伦敦塔桥",
    "sceneVariants": [
      {
        "id": "united-kingdom-london-tower-bridge--day-signature",
        "destinationId": "united-kingdom-london-tower-bridge",
        "imageSrc": "/scenes/scene--united-kingdom-london-tower-bridge--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.94,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-kingdom-london-tower-bridge--golden-hour",
        "destinationId": "united-kingdom-london-tower-bridge",
        "imageSrc": "/scenes/scene--united-kingdom-london-tower-bridge--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.94,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "italy-rome-colosseum",
    "name": "罗马斗兽场",
    "sceneVariants": [
      {
        "id": "italy-rome-colosseum--day-signature",
        "destinationId": "italy-rome-colosseum",
        "imageSrc": "/scenes/scene--italy-rome-colosseum--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.19,
          "y": 0.93,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "italy-rome-colosseum--golden-hour",
        "destinationId": "italy-rome-colosseum",
        "imageSrc": "/scenes/scene--italy-rome-colosseum--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.87,
          "y": 0.94,
          "scale": 0.2,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "egypt-giza-pyramids",
    "name": "吉萨金字塔",
    "sceneVariants": [
      {
        "id": "egypt-giza-pyramids--day-signature",
        "destinationId": "egypt-giza-pyramids",
        "imageSrc": "/scenes/scene--egypt-giza-pyramids--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "egypt-giza-pyramids--golden-hour",
        "destinationId": "egypt-giza-pyramids",
        "imageSrc": "/scenes/scene--egypt-giza-pyramids--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "egypt-giza-pyramids--companion-rare",
        "destinationId": "egypt-giza-pyramids",
        "imageSrc": "/scenes/scene--egypt-giza-pyramids--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "united-states-new-york-brooklyn-bridge",
    "name": "纽约布鲁克林大桥",
    "sceneVariants": [
      {
        "id": "united-states-new-york-brooklyn-bridge--day-signature",
        "destinationId": "united-states-new-york-brooklyn-bridge",
        "imageSrc": "/scenes/scene--united-states-new-york-brooklyn-bridge--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.3,
          "y": 0.85,
          "scale": 0.22,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-states-new-york-brooklyn-bridge--golden-hour",
        "destinationId": "united-states-new-york-brooklyn-bridge",
        "imageSrc": "/scenes/scene--united-states-new-york-brooklyn-bridge--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.3,
          "y": 0.85,
          "scale": 0.22,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "peru-cusco-machu-picchu",
    "name": "马丘比丘",
    "sceneVariants": [
      {
        "id": "peru-cusco-machu-picchu--day-signature",
        "destinationId": "peru-cusco-machu-picchu",
        "imageSrc": "/scenes/scene--peru-cusco-machu-picchu--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "peru-cusco-machu-picchu--golden-hour",
        "destinationId": "peru-cusco-machu-picchu",
        "imageSrc": "/scenes/scene--peru-cusco-machu-picchu--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-beijing-mutianyu-great-wall",
    "name": "慕田峪长城",
    "sceneVariants": [
      {
        "id": "china-beijing-mutianyu-great-wall--day-signature",
        "destinationId": "china-beijing-mutianyu-great-wall",
        "imageSrc": "/scenes/scene--china-beijing-mutianyu-great-wall--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.91,
          "scale": 0.31,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-beijing-mutianyu-great-wall--golden-hour",
        "destinationId": "china-beijing-mutianyu-great-wall",
        "imageSrc": "/scenes/scene--china-beijing-mutianyu-great-wall--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.23,
          "y": 0.91,
          "scale": 0.31,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-shanghai-the-bund",
    "name": "上海外滩",
    "sceneVariants": [
      {
        "id": "china-shanghai-the-bund--day-signature",
        "destinationId": "china-shanghai-the-bund",
        "imageSrc": "/scenes/scene--china-shanghai-the-bund--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.16,
          "y": 0.94,
          "scale": 0.26,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-shanghai-the-bund--golden-hour",
        "destinationId": "china-shanghai-the-bund",
        "imageSrc": "/scenes/scene--china-shanghai-the-bund--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.16,
          "y": 0.94,
          "scale": 0.26,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-xian-giant-wild-goose-pagoda",
    "name": "西安大雁塔",
    "sceneVariants": [
      {
        "id": "china-xian-giant-wild-goose-pagoda--day-signature",
        "destinationId": "china-xian-giant-wild-goose-pagoda",
        "imageSrc": "/scenes/scene--china-xian-giant-wild-goose-pagoda--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.82,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-xian-giant-wild-goose-pagoda--golden-hour",
        "destinationId": "china-xian-giant-wild-goose-pagoda",
        "imageSrc": "/scenes/scene--china-xian-giant-wild-goose-pagoda--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.82,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-guilin-elephant-trunk-hill",
    "name": "桂林象鼻山",
    "sceneVariants": [
      {
        "id": "china-guilin-elephant-trunk-hill--day-signature",
        "destinationId": "china-guilin-elephant-trunk-hill",
        "imageSrc": "/scenes/scene--china-guilin-elephant-trunk-hill--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.85,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-guilin-elephant-trunk-hill--golden-hour",
        "destinationId": "china-guilin-elephant-trunk-hill",
        "imageSrc": "/scenes/scene--china-guilin-elephant-trunk-hill--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.85,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-guilin-elephant-trunk-hill--companion-rare",
        "destinationId": "china-guilin-elephant-trunk-hill",
        "imageSrc": "/scenes/scene--china-guilin-elephant-trunk-hill--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.85,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "china-dongguan-xiliubeipo-village",
    "name": "东莞松山湖溪流背坡村",
    "sceneVariants": [
      {
        "id": "china-dongguan-xiliubeipo-village--day-signature",
        "destinationId": "china-dongguan-xiliubeipo-village",
        "imageSrc": "/scenes/scene--china-dongguan-xiliubeipo-village--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.83,
          "y": 0.93,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "china-dongguan-xiliubeipo-village--golden-hour",
        "destinationId": "china-dongguan-xiliubeipo-village",
        "imageSrc": "/scenes/scene--china-dongguan-xiliubeipo-village--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.835,
          "y": 0.93,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-hangzhou-west-lake-leifeng-pagoda",
    "name": "杭州西湖雷峰塔",
    "sceneVariants": [
      {
        "id": "china-hangzhou-west-lake-leifeng-pagoda--day-signature",
        "destinationId": "china-hangzhou-west-lake-leifeng-pagoda",
        "imageSrc": "/scenes/scene--china-hangzhou-west-lake-leifeng-pagoda--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.835,
          "y": 0.91,
          "scale": 0.32,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "china-hangzhou-west-lake-leifeng-pagoda--golden-hour",
        "destinationId": "china-hangzhou-west-lake-leifeng-pagoda",
        "imageSrc": "/scenes/scene--china-hangzhou-west-lake-leifeng-pagoda--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.195,
          "y": 0.91,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "india-agra-taj-mahal",
    "name": "阿格拉泰姬陵",
    "sceneVariants": [
      {
        "id": "india-agra-taj-mahal--day-signature",
        "destinationId": "india-agra-taj-mahal",
        "imageSrc": "/scenes/scene--india-agra-taj-mahal--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.85,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "india-agra-taj-mahal--golden-hour",
        "destinationId": "india-agra-taj-mahal",
        "imageSrc": "/scenes/scene--india-agra-taj-mahal--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.175,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "india-agra-taj-mahal--companion-rare",
        "destinationId": "india-agra-taj-mahal",
        "imageSrc": "/scenes/scene--india-agra-taj-mahal--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.85,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "turkey-istanbul-hagia-sophia",
    "name": "伊斯坦布尔圣索菲亚",
    "sceneVariants": [
      {
        "id": "turkey-istanbul-hagia-sophia--day-signature",
        "destinationId": "turkey-istanbul-hagia-sophia",
        "imageSrc": "/scenes/scene--turkey-istanbul-hagia-sophia--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.91,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "turkey-istanbul-hagia-sophia--golden-hour",
        "destinationId": "turkey-istanbul-hagia-sophia",
        "imageSrc": "/scenes/scene--turkey-istanbul-hagia-sophia--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "turkey-istanbul-hagia-sophia--companion-rare",
        "destinationId": "turkey-istanbul-hagia-sophia",
        "imageSrc": "/scenes/scene--turkey-istanbul-hagia-sophia--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.185,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "brazil-rio-de-janeiro-christ-the-redeemer",
    "name": "里约热内卢基督像",
    "sceneVariants": [
      {
        "id": "brazil-rio-de-janeiro-christ-the-redeemer--day-signature",
        "destinationId": "brazil-rio-de-janeiro-christ-the-redeemer",
        "imageSrc": "/scenes/scene--brazil-rio-de-janeiro-christ-the-redeemer--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.135,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "brazil-rio-de-janeiro-christ-the-redeemer--golden-hour",
        "destinationId": "brazil-rio-de-janeiro-christ-the-redeemer",
        "imageSrc": "/scenes/scene--brazil-rio-de-janeiro-christ-the-redeemer--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.32,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "south-africa-cape-town-table-mountain",
    "name": "开普敦桌山",
    "sceneVariants": [
      {
        "id": "south-africa-cape-town-table-mountain--day-signature",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/scenes/scene--south-africa-cape-town-table-mountain--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.17,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "south-africa-cape-town-table-mountain--golden-hour",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/scenes/scene--south-africa-cape-town-table-mountain--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.17,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "south-africa-cape-town-table-mountain--companion-rare",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/scenes/scene--south-africa-cape-town-table-mountain--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.17,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "mexico-yucatan-chichen-itza",
    "name": "奇琴伊察",
    "sceneVariants": [
      {
        "id": "mexico-yucatan-chichen-itza--day-signature",
        "destinationId": "mexico-yucatan-chichen-itza",
        "imageSrc": "/scenes/scene--mexico-yucatan-chichen-itza--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.83,
          "y": 0.94,
          "scale": 0.22,
          "pose": "sit",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "mexico-yucatan-chichen-itza--golden-hour",
        "destinationId": "mexico-yucatan-chichen-itza",
        "imageSrc": "/scenes/scene--mexico-yucatan-chichen-itza--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.16,
          "y": 0.94,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "mexico-yucatan-chichen-itza--companion-rare",
        "destinationId": "mexico-yucatan-chichen-itza",
        "imageSrc": "/scenes/scene--mexico-yucatan-chichen-itza--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.84,
          "y": 0.94,
          "scale": 0.21,
          "pose": "sit",
          "flip": true
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "jordan-petra-al-khazneh",
    "name": "佩特拉卡兹尼神殿",
    "sceneVariants": [
      {
        "id": "jordan-petra-al-khazneh--day-signature",
        "destinationId": "jordan-petra-al-khazneh",
        "imageSrc": "/scenes/scene--jordan-petra-al-khazneh--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.27,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "jordan-petra-al-khazneh--golden-hour",
        "destinationId": "jordan-petra-al-khazneh",
        "imageSrc": "/scenes/scene--jordan-petra-al-khazneh--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.72,
          "y": 0.92,
          "scale": 0.28,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "cambodia-siem-reap-angkor-wat",
    "name": "吴哥窟",
    "sceneVariants": [
      {
        "id": "cambodia-siem-reap-angkor-wat--day-signature",
        "destinationId": "cambodia-siem-reap-angkor-wat",
        "imageSrc": "/scenes/scene--cambodia-siem-reap-angkor-wat--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "cambodia-siem-reap-angkor-wat--golden-hour",
        "destinationId": "cambodia-siem-reap-angkor-wat",
        "imageSrc": "/scenes/scene--cambodia-siem-reap-angkor-wat--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "cambodia-siem-reap-angkor-wat--companion-rare",
        "destinationId": "cambodia-siem-reap-angkor-wat",
        "imageSrc": "/scenes/scene--cambodia-siem-reap-angkor-wat--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "new-zealand-fiordland-milford-sound",
    "name": "米尔福德峡湾",
    "sceneVariants": [
      {
        "id": "new-zealand-fiordland-milford-sound--day-signature",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/scenes/scene--new-zealand-fiordland-milford-sound--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "new-zealand-fiordland-milford-sound--golden-hour",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/scenes/scene--new-zealand-fiordland-milford-sound--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "new-zealand-fiordland-milford-sound--companion-rare",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/scenes/scene--new-zealand-fiordland-milford-sound--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "morocco-ouarzazate-ait-benhaddou",
    "name": "艾本哈杜村",
    "sceneVariants": [
      {
        "id": "morocco-ouarzazate-ait-benhaddou--day-signature",
        "destinationId": "morocco-ouarzazate-ait-benhaddou",
        "imageSrc": "/scenes/scene--morocco-ouarzazate-ait-benhaddou--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.175,
          "y": 0.94,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "morocco-ouarzazate-ait-benhaddou--golden-hour",
        "destinationId": "morocco-ouarzazate-ait-benhaddou",
        "imageSrc": "/scenes/scene--morocco-ouarzazate-ait-benhaddou--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.83,
          "y": 0.94,
          "scale": 0.29,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  }
] as const satisfies readonly Destination[]
