// Generated by scripts/integrate-latest-art.mjs. Do not edit by hand.
import type { Destination, PortraitPose } from './index'

export const DEV_LATEST_ART_METADATA = {
  integration: 'development-preview-only',
  shippingEligible: false,
  productionPromotion: 'not-promoted',
  runtimeAssetRoot: '/dev-art/latest-v5',
  landmarkV5: {
    manifest: 'docs/art/candidates/landmarks/manifest.candidates.v5.json',
    manifestSha256: '7efae429086d85dadd024a717547d1320186bf9628f4787ae3ba4fbee2a6cd5a',
    sceneSetRevision: 'b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669',
    destinationCount: 25,
    sceneCount: 76,
    candidateApprovalState: 'pending-human-approval',
    visualApproval: 'approved-for-v5-candidate-scope-only',
    productionApproval: 'not-promoted',
    rightsAndShipping: 'pending-separate-gates',
  },
  minhoWatercolorV2: {
    manifest: 'docs/art/candidates/portraits/minho-watercolor-v2/manifest.candidate.json',
    portraitSetRevision: '0634b7b70df8e80857844f6914599faeca2def64ddccc4dcd0384b77abf257ca',
    poseCount: 10,
    candidateReview: 'pending-human-review',
    machineQa: 'pass',
    productionApproval: 'not-promoted',
  },
  compositeQa: {
    manifest: 'docs/art/reviews/portraits/minho-watercolor-v2/composites-v5/manifest.json',
    status: 'pending-human-review',
    selectableScenePoseIds: ["gaze","sit","sleep","walk"],
    pendingDedicatedScenePoseIds: ["eat","greet","play","reach","sniff","stretch"],
  },
  cinematic: {
    included: false,
    reason: 'cinematic assets remain an isolated dormant candidate set',
  },
} as const

export const DEV_LATEST_ART_SCENE_SET_REVISION = 'b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669' as const
export const DEV_LATEST_ART_PORTRAIT_SET_REVISION = '0634b7b70df8e80857844f6914599faeca2def64ddccc4dcd0384b77abf257ca' as const

export const DEV_LATEST_ART_DESTINATIONS = [
  {
    "id": "china-beijing-forbidden-city-corner-tower",
    "name": "故宫角楼",
    "sceneVariants": [
      {
        "id": "china-beijing-forbidden-city-corner-tower--day-signature",
        "destinationId": "china-beijing-forbidden-city-corner-tower",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-beijing-forbidden-city-corner-tower--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.79,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-beijing-forbidden-city-corner-tower--golden-hour",
        "destinationId": "china-beijing-forbidden-city-corner-tower",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-beijing-forbidden-city-corner-tower--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.91,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "japan-kyoto-fushimi-inari-taisha",
    "name": "京都伏见稻荷",
    "sceneVariants": [
      {
        "id": "japan-kyoto-fushimi-inari-taisha--day-signature",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--japan-kyoto-fushimi-inari-taisha--day-signature--v03.webp",
        "compositionSlot": {
          "x": 0.34,
          "y": 0.79,
          "scale": 0.135,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "japan-kyoto-fushimi-inari-taisha--golden-hour",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--japan-kyoto-fushimi-inari-taisha--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.805,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "japan-kyoto-fushimi-inari-taisha--companion-rare",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--japan-kyoto-fushimi-inari-taisha--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      },
      {
        "id": "japan-kyoto-fushimi-inari-taisha--night-transit",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--japan-kyoto-fushimi-inari-taisha--night-transit--v02.webp",
        "compositionSlot": {
          "x": 0.54,
          "y": 0.605,
          "scale": 0.075,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "japan-kyoto-fushimi-inari-taisha--sheltered-rest",
        "destinationId": "japan-kyoto-fushimi-inari-taisha",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--japan-kyoto-fushimi-inari-taisha--sheltered-rest--v01.webp",
        "compositionSlot": {
          "x": 0.23,
          "y": 0.84,
          "scale": 0.2,
          "pose": "sleep",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "singapore-singapore-merlion",
    "name": "新加坡鱼尾狮",
    "sceneVariants": [
      {
        "id": "singapore-singapore-merlion--day-signature",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--singapore-singapore-merlion--day-signature--v03.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.93,
          "scale": 0.22,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "singapore-singapore-merlion--golden-hour",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--singapore-singapore-merlion--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "singapore-singapore-merlion--companion-rare",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--singapore-singapore-merlion--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      },
      {
        "id": "singapore-singapore-merlion--night-transit",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--singapore-singapore-merlion--night-transit--v02.webp",
        "compositionSlot": {
          "x": 0.34,
          "y": 0.82,
          "scale": 0.125,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "singapore-singapore-merlion--sheltered-rest",
        "destinationId": "singapore-singapore-merlion",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--singapore-singapore-merlion--sheltered-rest--v01.webp",
        "compositionSlot": {
          "x": 0.29,
          "y": 0.86,
          "scale": 0.2,
          "pose": "sleep",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "australia-sydney-opera-house",
    "name": "悉尼歌剧院",
    "sceneVariants": [
      {
        "id": "australia-sydney-opera-house--day-signature",
        "destinationId": "australia-sydney-opera-house",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--australia-sydney-opera-house--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.89,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "australia-sydney-opera-house--golden-hour",
        "destinationId": "australia-sydney-opera-house",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--australia-sydney-opera-house--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.89,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "australia-sydney-opera-house--companion-rare",
        "destinationId": "australia-sydney-opera-house",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--australia-sydney-opera-house--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.89,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "france-paris-eiffel-tower",
    "name": "巴黎埃菲尔铁塔",
    "sceneVariants": [
      {
        "id": "france-paris-eiffel-tower--day-signature",
        "destinationId": "france-paris-eiffel-tower",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--france-paris-eiffel-tower--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.89,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "france-paris-eiffel-tower--golden-hour",
        "destinationId": "france-paris-eiffel-tower",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--france-paris-eiffel-tower--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.2,
          "y": 0.89,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "united-kingdom-london-tower-bridge",
    "name": "伦敦塔桥",
    "sceneVariants": [
      {
        "id": "united-kingdom-london-tower-bridge--day-signature",
        "destinationId": "united-kingdom-london-tower-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-kingdom-london-tower-bridge--day-signature--v03.webp",
        "compositionSlot": {
          "x": 0.42,
          "y": 0.94,
          "scale": 0.22,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-kingdom-london-tower-bridge--golden-hour",
        "destinationId": "united-kingdom-london-tower-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-kingdom-london-tower-bridge--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.94,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-kingdom-london-tower-bridge--night-transit",
        "destinationId": "united-kingdom-london-tower-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-kingdom-london-tower-bridge--night-transit--v02.webp",
        "compositionSlot": {
          "x": 0.43,
          "y": 0.79,
          "scale": 0.125,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-kingdom-london-tower-bridge--sheltered-rest",
        "destinationId": "united-kingdom-london-tower-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-kingdom-london-tower-bridge--sheltered-rest--v01.webp",
        "compositionSlot": {
          "x": 0.42,
          "y": 0.8,
          "scale": 0.16,
          "pose": "sleep",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "italy-rome-colosseum",
    "name": "罗马斗兽场",
    "sceneVariants": [
      {
        "id": "italy-rome-colosseum--day-signature",
        "destinationId": "italy-rome-colosseum",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--italy-rome-colosseum--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.19,
          "y": 0.93,
          "scale": 0.27,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "italy-rome-colosseum--golden-hour",
        "destinationId": "italy-rome-colosseum",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--italy-rome-colosseum--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.87,
          "y": 0.94,
          "scale": 0.2,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "egypt-giza-pyramids",
    "name": "吉萨金字塔",
    "sceneVariants": [
      {
        "id": "egypt-giza-pyramids--day-signature",
        "destinationId": "egypt-giza-pyramids",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--egypt-giza-pyramids--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "egypt-giza-pyramids--golden-hour",
        "destinationId": "egypt-giza-pyramids",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--egypt-giza-pyramids--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "egypt-giza-pyramids--companion-rare",
        "destinationId": "egypt-giza-pyramids",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--egypt-giza-pyramids--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.9,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "united-states-new-york-brooklyn-bridge",
    "name": "纽约布鲁克林大桥",
    "sceneVariants": [
      {
        "id": "united-states-new-york-brooklyn-bridge--day-signature",
        "destinationId": "united-states-new-york-brooklyn-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-states-new-york-brooklyn-bridge--day-signature--v03.webp",
        "compositionSlot": {
          "x": 0.31,
          "y": 0.79,
          "scale": 0.135,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-states-new-york-brooklyn-bridge--golden-hour",
        "destinationId": "united-states-new-york-brooklyn-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-states-new-york-brooklyn-bridge--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.3,
          "y": 0.85,
          "scale": 0.22,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-states-new-york-brooklyn-bridge--night-transit",
        "destinationId": "united-states-new-york-brooklyn-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-states-new-york-brooklyn-bridge--night-transit--v02.webp",
        "compositionSlot": {
          "x": 0.55,
          "y": 0.64,
          "scale": 0.08,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "united-states-new-york-brooklyn-bridge--sheltered-rest",
        "destinationId": "united-states-new-york-brooklyn-bridge",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--united-states-new-york-brooklyn-bridge--sheltered-rest--v01.webp",
        "compositionSlot": {
          "x": 0.3,
          "y": 0.82,
          "scale": 0.13,
          "pose": "sleep",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "peru-cusco-machu-picchu",
    "name": "马丘比丘",
    "sceneVariants": [
      {
        "id": "peru-cusco-machu-picchu--day-signature",
        "destinationId": "peru-cusco-machu-picchu",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--peru-cusco-machu-picchu--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "peru-cusco-machu-picchu--golden-hour",
        "destinationId": "peru-cusco-machu-picchu",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--peru-cusco-machu-picchu--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.88,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "peru-cusco-machu-picchu--distant-overlook",
        "destinationId": "peru-cusco-machu-picchu",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--peru-cusco-machu-picchu--distant-overlook--v01.webp",
        "compositionSlot": {
          "x": 0.19,
          "y": 0.77,
          "scale": 0.07,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-beijing-mutianyu-great-wall",
    "name": "慕田峪长城",
    "sceneVariants": [
      {
        "id": "china-beijing-mutianyu-great-wall--day-signature",
        "destinationId": "china-beijing-mutianyu-great-wall",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-beijing-mutianyu-great-wall--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.91,
          "scale": 0.31,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-beijing-mutianyu-great-wall--golden-hour",
        "destinationId": "china-beijing-mutianyu-great-wall",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-beijing-mutianyu-great-wall--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.23,
          "y": 0.91,
          "scale": 0.31,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-beijing-mutianyu-great-wall--distant-overlook",
        "destinationId": "china-beijing-mutianyu-great-wall",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-beijing-mutianyu-great-wall--distant-overlook--v01.webp",
        "compositionSlot": {
          "x": 0.44,
          "y": 0.75,
          "scale": 0.065,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-shanghai-the-bund",
    "name": "上海外滩",
    "sceneVariants": [
      {
        "id": "china-shanghai-the-bund--day-signature",
        "destinationId": "china-shanghai-the-bund",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-shanghai-the-bund--day-signature--v03.webp",
        "compositionSlot": {
          "x": 0.13,
          "y": 0.94,
          "scale": 0.21,
          "pose": "walk",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-shanghai-the-bund--golden-hour",
        "destinationId": "china-shanghai-the-bund",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-shanghai-the-bund--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.16,
          "y": 0.94,
          "scale": 0.26,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-shanghai-the-bund--night-transit",
        "destinationId": "china-shanghai-the-bund",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-shanghai-the-bund--night-transit--v02.webp",
        "compositionSlot": {
          "x": 0.47,
          "y": 0.67,
          "scale": 0.08,
          "pose": "walk",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "china-shanghai-the-bund--sheltered-rest",
        "destinationId": "china-shanghai-the-bund",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-shanghai-the-bund--sheltered-rest--v01.webp",
        "compositionSlot": {
          "x": 0.31,
          "y": 0.89,
          "scale": 0.22,
          "pose": "sleep",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-xian-giant-wild-goose-pagoda",
    "name": "西安大雁塔",
    "sceneVariants": [
      {
        "id": "china-xian-giant-wild-goose-pagoda--day-signature",
        "destinationId": "china-xian-giant-wild-goose-pagoda",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-xian-giant-wild-goose-pagoda--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.82,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-xian-giant-wild-goose-pagoda--golden-hour",
        "destinationId": "china-xian-giant-wild-goose-pagoda",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-xian-giant-wild-goose-pagoda--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.22,
          "y": 0.82,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-guilin-elephant-trunk-hill",
    "name": "桂林象鼻山",
    "sceneVariants": [
      {
        "id": "china-guilin-elephant-trunk-hill--day-signature",
        "destinationId": "china-guilin-elephant-trunk-hill",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-guilin-elephant-trunk-hill--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.85,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-guilin-elephant-trunk-hill--golden-hour",
        "destinationId": "china-guilin-elephant-trunk-hill",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-guilin-elephant-trunk-hill--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.85,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "china-guilin-elephant-trunk-hill--companion-rare",
        "destinationId": "china-guilin-elephant-trunk-hill",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-guilin-elephant-trunk-hill--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.15,
          "y": 0.85,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "china-dongguan-xiliubeipo-village",
    "name": "东莞松山湖溪流背坡村",
    "sceneVariants": [
      {
        "id": "china-dongguan-xiliubeipo-village--day-signature",
        "destinationId": "china-dongguan-xiliubeipo-village",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-dongguan-xiliubeipo-village--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.83,
          "y": 0.93,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "china-dongguan-xiliubeipo-village--golden-hour",
        "destinationId": "china-dongguan-xiliubeipo-village",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-dongguan-xiliubeipo-village--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.835,
          "y": 0.93,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "china-hangzhou-west-lake-leifeng-pagoda",
    "name": "杭州西湖雷峰塔",
    "sceneVariants": [
      {
        "id": "china-hangzhou-west-lake-leifeng-pagoda--day-signature",
        "destinationId": "china-hangzhou-west-lake-leifeng-pagoda",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-hangzhou-west-lake-leifeng-pagoda--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.835,
          "y": 0.91,
          "scale": 0.32,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "china-hangzhou-west-lake-leifeng-pagoda--golden-hour",
        "destinationId": "china-hangzhou-west-lake-leifeng-pagoda",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--china-hangzhou-west-lake-leifeng-pagoda--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.195,
          "y": 0.91,
          "scale": 0.32,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "india-agra-taj-mahal",
    "name": "阿格拉泰姬陵",
    "sceneVariants": [
      {
        "id": "india-agra-taj-mahal--day-signature",
        "destinationId": "india-agra-taj-mahal",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--india-agra-taj-mahal--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.85,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "india-agra-taj-mahal--golden-hour",
        "destinationId": "india-agra-taj-mahal",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--india-agra-taj-mahal--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.175,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "india-agra-taj-mahal--companion-rare",
        "destinationId": "india-agra-taj-mahal",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--india-agra-taj-mahal--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.85,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "turkey-istanbul-hagia-sophia",
    "name": "伊斯坦布尔圣索菲亚",
    "sceneVariants": [
      {
        "id": "turkey-istanbul-hagia-sophia--day-signature",
        "destinationId": "turkey-istanbul-hagia-sophia",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--turkey-istanbul-hagia-sophia--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.18,
          "y": 0.91,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "turkey-istanbul-hagia-sophia--golden-hour",
        "destinationId": "turkey-istanbul-hagia-sophia",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--turkey-istanbul-hagia-sophia--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.825,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "turkey-istanbul-hagia-sophia--companion-rare",
        "destinationId": "turkey-istanbul-hagia-sophia",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--turkey-istanbul-hagia-sophia--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.185,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "brazil-rio-de-janeiro-christ-the-redeemer",
    "name": "里约热内卢基督像",
    "sceneVariants": [
      {
        "id": "brazil-rio-de-janeiro-christ-the-redeemer--day-signature",
        "destinationId": "brazil-rio-de-janeiro-christ-the-redeemer",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--brazil-rio-de-janeiro-christ-the-redeemer--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.135,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "brazil-rio-de-janeiro-christ-the-redeemer--golden-hour",
        "destinationId": "brazil-rio-de-janeiro-christ-the-redeemer",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--brazil-rio-de-janeiro-christ-the-redeemer--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.32,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "south-africa-cape-town-table-mountain",
    "name": "开普敦桌山",
    "sceneVariants": [
      {
        "id": "south-africa-cape-town-table-mountain--day-signature",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--south-africa-cape-town-table-mountain--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.17,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "south-africa-cape-town-table-mountain--golden-hour",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--south-africa-cape-town-table-mountain--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.17,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "south-africa-cape-town-table-mountain--companion-rare",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--south-africa-cape-town-table-mountain--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.17,
          "y": 0.92,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      },
      {
        "id": "south-africa-cape-town-table-mountain--distant-overlook",
        "destinationId": "south-africa-cape-town-table-mountain",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--south-africa-cape-town-table-mountain--distant-overlook--v01.webp",
        "compositionSlot": {
          "x": 0.3,
          "y": 0.72,
          "scale": 0.07,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "mexico-yucatan-chichen-itza",
    "name": "奇琴伊察",
    "sceneVariants": [
      {
        "id": "mexico-yucatan-chichen-itza--day-signature",
        "destinationId": "mexico-yucatan-chichen-itza",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--mexico-yucatan-chichen-itza--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.83,
          "y": 0.94,
          "scale": 0.22,
          "pose": "sit",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "mexico-yucatan-chichen-itza--golden-hour",
        "destinationId": "mexico-yucatan-chichen-itza",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--mexico-yucatan-chichen-itza--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.16,
          "y": 0.94,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "mexico-yucatan-chichen-itza--companion-rare",
        "destinationId": "mexico-yucatan-chichen-itza",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--mexico-yucatan-chichen-itza--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.84,
          "y": 0.94,
          "scale": 0.21,
          "pose": "sit",
          "flip": true
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "jordan-petra-al-khazneh",
    "name": "佩特拉卡兹尼神殿",
    "sceneVariants": [
      {
        "id": "jordan-petra-al-khazneh--day-signature",
        "destinationId": "jordan-petra-al-khazneh",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--jordan-petra-al-khazneh--day-signature--v02.webp",
        "compositionSlot": {
          "x": 0.27,
          "y": 0.92,
          "scale": 0.3,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "jordan-petra-al-khazneh--golden-hour",
        "destinationId": "jordan-petra-al-khazneh",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--jordan-petra-al-khazneh--golden-hour--v02.webp",
        "compositionSlot": {
          "x": 0.72,
          "y": 0.92,
          "scale": 0.28,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "cambodia-siem-reap-angkor-wat",
    "name": "吴哥窟",
    "sceneVariants": [
      {
        "id": "cambodia-siem-reap-angkor-wat--day-signature",
        "destinationId": "cambodia-siem-reap-angkor-wat",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--cambodia-siem-reap-angkor-wat--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "cambodia-siem-reap-angkor-wat--golden-hour",
        "destinationId": "cambodia-siem-reap-angkor-wat",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--cambodia-siem-reap-angkor-wat--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "cambodia-siem-reap-angkor-wat--companion-rare",
        "destinationId": "cambodia-siem-reap-angkor-wat",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--cambodia-siem-reap-angkor-wat--companion-rare--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.28,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      }
    ]
  },
  {
    "id": "new-zealand-fiordland-milford-sound",
    "name": "米尔福德峡湾",
    "sceneVariants": [
      {
        "id": "new-zealand-fiordland-milford-sound--day-signature",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--new-zealand-fiordland-milford-sound--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "new-zealand-fiordland-milford-sound--golden-hour",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--new-zealand-fiordland-milford-sound--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "new-zealand-fiordland-milford-sound--companion-rare",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--new-zealand-fiordland-milford-sound--companion-rare--v02.webp",
        "compositionSlot": {
          "x": 0.5,
          "y": 0.93,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": true
      },
      {
        "id": "new-zealand-fiordland-milford-sound--distant-overlook",
        "destinationId": "new-zealand-fiordland-milford-sound",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--new-zealand-fiordland-milford-sound--distant-overlook--v01.webp",
        "compositionSlot": {
          "x": 0.28,
          "y": 0.79,
          "scale": 0.085,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      }
    ]
  },
  {
    "id": "morocco-ouarzazate-ait-benhaddou",
    "name": "艾本哈杜村",
    "sceneVariants": [
      {
        "id": "morocco-ouarzazate-ait-benhaddou--day-signature",
        "destinationId": "morocco-ouarzazate-ait-benhaddou",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--morocco-ouarzazate-ait-benhaddou--day-signature--v01.webp",
        "compositionSlot": {
          "x": 0.175,
          "y": 0.94,
          "scale": 0.29,
          "pose": "gaze",
          "flip": false
        },
        "hasCompanion": false
      },
      {
        "id": "morocco-ouarzazate-ait-benhaddou--golden-hour",
        "destinationId": "morocco-ouarzazate-ait-benhaddou",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--morocco-ouarzazate-ait-benhaddou--golden-hour--v01.webp",
        "compositionSlot": {
          "x": 0.83,
          "y": 0.94,
          "scale": 0.29,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      },
      {
        "id": "morocco-ouarzazate-ait-benhaddou--distant-overlook",
        "destinationId": "morocco-ouarzazate-ait-benhaddou",
        "imageSrc": "/dev-art/latest-v5/scenes/scene--morocco-ouarzazate-ait-benhaddou--distant-overlook--v01.webp",
        "compositionSlot": {
          "x": 0.77,
          "y": 0.84,
          "scale": 0.08,
          "pose": "gaze",
          "flip": true
        },
        "hasCompanion": false
      }
    ]
  }
] as const satisfies readonly Destination[]

export const DEV_LATEST_ART_SCENE_REVISIONS = {
  "china-beijing-forbidden-city-corner-tower--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:3f8007be31b28d37db9f78375be2c3865927d32f69eab2abd954fe4b6961381b:d8de05bde699561c56bca25ab5950a83967e34076bc624e0af61062201f93d1c",
  "china-beijing-forbidden-city-corner-tower--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:cae884ec8ace36f04b110b5f3791be432a037a510f7d6ba265258e63e330959f:75c8f031bd87576e6ee06615e146b1c45929fd60bbe859f7f83d318d50a23447",
  "japan-kyoto-fushimi-inari-taisha--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:394378cb7fce0011dbbcc531b617b3baf0cb565fc16bf2ad26f0d368e2a55f59:c402ba4b43507f33a0049647081749eaec449233af1d52d8963fccaace276830",
  "japan-kyoto-fushimi-inari-taisha--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:5bca6c24875d1e0e29604b63c593fa3f46daa3613bfc0a98705e8af240cdb4ee:e34b27f590454d2d5c5aea70ed994c5753742aca01a73cc61869b4ff7f93e2a4",
  "japan-kyoto-fushimi-inari-taisha--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:483e37f25491404a5f071337c1f35db4547e13d38d5711f308afdad8fe130ec3:fbfdd7d6e27a7b304ec5949f516ccdbb0cc6d8dc330faa314f79c6b2b2c83302",
  "japan-kyoto-fushimi-inari-taisha--night-transit": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:159ea8f6f88c79983b455499cfa63f91a54386ee93bf288f3669c12fd7540666:e8e85cb842dbe874bcb302da70619a6a11c285e060faf200d8fbee0b5cd309f9",
  "japan-kyoto-fushimi-inari-taisha--sheltered-rest": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:521b639a6e6ab1dbf11d1154e96990f3da0126830900c3c5f87cf0a0e8cd1cc2:c39514283fcb3d3926ebe2216f9df910e4a13f39b7a221530b85617acc19ef2d",
  "singapore-singapore-merlion--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:00213fca355b7ceff56b683a1657f65dabdb20b56b054f794393e9fedaf44318:c59045fdff2b643611e4009ee834e7a33f55ad1b167578fb2f314a89f3038e95",
  "singapore-singapore-merlion--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:39f8f3cf7157c36e357d9cb37f6bfa143c3082296aa58071636f84c85dae61bd:d14da1a2e9db3d843ede11a520540f1cef2fd23b4974081b800933b68d3909f4",
  "singapore-singapore-merlion--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:1bc620e369e3045d7f56f506154511c2dd884faa448a13157bca7f1a4719823a:e6bd5de153e7a38276d7e0eb01dee72a968a7ba7476edc07efe1d84587fa60fb",
  "singapore-singapore-merlion--night-transit": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:dd08f3990ad7d3d8b48bd2c747a976355b29f736bf2ee16067e42f6ad4d184ff:152b24ec524f53e893d88e6caf9b84e259f51582c6e3cfa7486da81b6bbe2f67",
  "singapore-singapore-merlion--sheltered-rest": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:e8e80a610c9eb909f70c3dccc8d2258e28636562b57ca01c335feb3421d41361:6d930f0af3f75ea496a8d5e9ad3f96076683895e0c69e1aae4d5d4b51958b84f",
  "australia-sydney-opera-house--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:586f6c12f5a61d259170809594f8f25db767477731dc8396ffc941f856188274:0371f0f021eaaa36c4c935c9c093517649743a5eab40891e37c75fd0e9b8659f",
  "australia-sydney-opera-house--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:2b59022e50558fb9ea8c9f62bbc8d7b75eef440783ead148a4230ac462d92871:ebc1b1b5390dc3afb2716d241fc27771a4c9b1d613355bfd72f0cb7addd4525e",
  "australia-sydney-opera-house--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:a36ba0e649bbc304a3c0bfa414f9c86b85e39aba699d722b49ec36d383553481:48fb153130450b705479a776a08ed9cb4799ae74721c6317b194953fd7aa873e",
  "france-paris-eiffel-tower--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:b23c9c62bd4860b754e755e161cc4a97b6e94d2eb09eb521a6ed3b392a139bab:abed437c3c193742b465e8dc289a534a82bd94304f08e12935607ab6ed6c673e",
  "france-paris-eiffel-tower--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:1f5719b499f9d7cd1f11acb784850078527328e7094e8d0b113a422a18860dd2:8759dec3cdf7c295b887a7fdba5b60bec63246df3f7b7fb323e882c3b7f766c0",
  "united-kingdom-london-tower-bridge--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:0e119d82a608d7eef656792053c02bd693ff836b269f09445d3c2c51d700b4d3:10f859aa02bdd35890663b47f21d3dd7163622ede2b0697476d06ee4b624de49",
  "united-kingdom-london-tower-bridge--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:30e84dc9bfc8e31e16a7450d70f27cac78e5f5de17a0937ba94700f56207c262:42df0b0705d4d4727714515bb29a0e58f8982323b8107ff9043bf8b575d91eff",
  "united-kingdom-london-tower-bridge--night-transit": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:a43b6173e30166aab65acc03e36dde3d7f8c7e11c11333d7280003671a26db17:b0507d6bd473187c63e4b8e0a18c9a276600bda39e33ab574335d6d274d00785",
  "united-kingdom-london-tower-bridge--sheltered-rest": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:0fb9e310746204503b8558cf8f3d96d4772ca4e2449140e45f358ccc1b917c15:f7ed4a710269d8464dd4bb7640fea9349fc7d93c45d9fdd5ea785102d0779f69",
  "italy-rome-colosseum--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:c5659c8da65731c86d148cb6c5046065b16f9ba7e773c2fde020d58ac5e17058:296664b0a1a838c3c35f1deed566b4df8194996b73d8859d54f13c1ec7a46e24",
  "italy-rome-colosseum--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:f0488c78e905e3bf98d9b79510eb6dedd287a9474701b4e17a038fa892a67904:f7a88b39ce571fd14a04ee561867b241a0825caaeab787b23dd57dd59bf6d094",
  "egypt-giza-pyramids--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:b74fcef69632e6c32c9018ee207dd2c97a83a1d25eb3f4ed412e8b5b91dd686e:182e97b28c296b76be1c03eac67feae53f9c37fc61b30204908dfd9f647ab3e0",
  "egypt-giza-pyramids--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:51219eea90a761064a968ad14fecc57d09e743f108538b42aad7581ce226b250:dc484c3833b03ffe9b6a8046c92725e5f88ea0294750eb41000d15f89e267a0e",
  "egypt-giza-pyramids--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:aca9f96c216bd9dcb7be475abca91a19828cbe61c5ef37dcfc5655783d0c7211:f0c2ccfdd6739a6aabe5b59e6acc1694e628ecd417627c914d6354e950966e33",
  "united-states-new-york-brooklyn-bridge--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:3cb33160028c5532c4ab580d4e12b18739d78fd90207cc44cfab50199ebddddd:91a7c15f94365589acb6ca44c47490893efac73b0ba68a9556880f8cc71528cb",
  "united-states-new-york-brooklyn-bridge--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:1c3ec44e08573689a0e5107d3cab701564766e3a43876b24658a3829e0b1ad06:bbe5b52aa5471768509382ce334437e10b21db74efc03f3d654ca11adcd372a4",
  "united-states-new-york-brooklyn-bridge--night-transit": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:7d164778605d90f8d8576e4b6e1f9b566c337630b76678feaed9e51817ef7d5d:4dbedbe04a36f7e1e2fa1d97a16b75f033c0596d7b7a9ea98d1c61cdf29bb684",
  "united-states-new-york-brooklyn-bridge--sheltered-rest": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:c6277073f28f5a2ba542e0d9d0f06aff6edcab322f355ad6d0fa143b46e5d18b:5f017d56c674b24dfb792aca61e789023b287f1f78bacfb1f0d0f4383fc3ecd0",
  "peru-cusco-machu-picchu--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:b8e1209e90686370fb8a37ae0f863beca058dac0fab3e8cedafcecf0523879f4:d1da13f1e1aaddd8c2a63b9d8f339dfe4b63d43b53cda467df4078e6761d8e49",
  "peru-cusco-machu-picchu--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:7d01821919b48acf57d10e51376e05f3229d40bdf2cb942620b3b842b4e00f32:aa9806b829ee4bb1292699fba24dfd9952bc468eef3dc0518864a6455702f997",
  "peru-cusco-machu-picchu--distant-overlook": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:7b83eeb9eabcfd1c36d2ad3ae25e20aaf14e622efab1f958cd208160ad8983f8:a587bc76d5c15ab18ac19913958b9c26871d122adcf823f45fb0d37fac3fe5a7",
  "china-beijing-mutianyu-great-wall--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:845b58c7c63742138863c843529c2f6f33ec5bbfd0757722bd19a89cb3fcc900:b83e8563e77f2ec4c714944c79a241034053b310b8d7c38b42e143376b117863",
  "china-beijing-mutianyu-great-wall--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:c4ca7694b0e4bce7c7faf8f182764656adecb1944f05676efa4987fa73eed022:cc90afd1835548d145c04c505c72a9d8f9cc7b5d885ccf2b01e039a8b54a5527",
  "china-beijing-mutianyu-great-wall--distant-overlook": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:9be7d1e857cb5a847f81bf6ecc84869cb49aa7f22fd88ce16868e454930bffff:b44eed2a67a37a9ae10fbf75a5de7a0c5d0a4045d83f2eb35a7767ada3b975dd",
  "china-shanghai-the-bund--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:c7934b03f5a95d9ed2cb23e66bcfddf842583b17f36c2c0e527c0b312963d7e3:cf7030a8c38c3f4398cc0a2ba366c93d895f4f8c73eb442dbba948362d88dea2",
  "china-shanghai-the-bund--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:fecd9110f79c550111ec1d51cb7bbcd1fdb51a08f664d04df7f6ff2a8c775752:0db5b61d78ab843ef915d12af5ef43e3ec333b861b89eae3403c55f5793ad7a6",
  "china-shanghai-the-bund--night-transit": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:416e8c6ae9dbee55350415f7fa2bd0aed0687aeb68a0618d05490655844f5d50:4f31a92d9aaa24f51694622ae7c365519fc21b2b4e4461079ca796c869f45d29",
  "china-shanghai-the-bund--sheltered-rest": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:fa34e63f3cf3b17ddec16652f623ea13a30e10407e22ec9c880da220e4be5194:84a94c4683b42e07a8d62e156ff39768a18e5d80e39b8f3efe26f18d106f6edf",
  "china-xian-giant-wild-goose-pagoda--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:1ed5bca2814181c5821dbf84e8bab8645625f66f328d90770304d37fe1e7a1a7:23c5a2ee4b01c8cbfa6041ee27db96f2f31fb9436c4a7e70eb695697d006e9be",
  "china-xian-giant-wild-goose-pagoda--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:24fb1d31e654f9688d5d33720ddb4a687bdc99a9ef85373af7793b6a9813f909:4f4692c2fb63a2e298c38f091751869bfda1315fba4cc6701ef48b0f92f3e779",
  "china-guilin-elephant-trunk-hill--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:ebed0474ee6671fd9654cadeef8a189484df0a163ba4f6169cb787884ee49e72:83324528d66ead40ca7047cef793f5431ecf6b731f01afeee5aff7c5ac6674c5",
  "china-guilin-elephant-trunk-hill--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:147073907c4ac282554c578703b8c684a7086678027b8af772f218fad145e5bd:9b7410d8d92c8931a62069b80c008bcd24204c957c7c5aaa9ecc447daa023ecd",
  "china-guilin-elephant-trunk-hill--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:781ed6f583956e3d1f7250672ad6f2aaf7bdac5e7a0ee0a457a3e672713567f2:c815388ed52678b67d79fe44c2d72433af1fbbd3cf1bc9691536a93b68aa32de",
  "china-dongguan-xiliubeipo-village--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:68a878ce60954bf8bb9a0211e58dc8b566e60a6bb9946b97383b49ff26f81c21:4495c83bcaec7586a096783d66dd553ac6689235fa51671dfbfedfdcef6bd58c",
  "china-dongguan-xiliubeipo-village--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:359aaaee5f65ce04aa8ac620f1ab61307846883dec0a7b5c4a14957b0c8c1127:20ec1ece503fa4042384b6edd5946fad715b03a6ca6f17e13f817e40df748007",
  "china-hangzhou-west-lake-leifeng-pagoda--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:600ca5d260cd50cbae034fd83779580ed24fce44398a32aea7ce00cb5df549d2:c6d756f033c0105354dd104b115df649b9a01ef2e78fd10878a3aa03bf242afe",
  "china-hangzhou-west-lake-leifeng-pagoda--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:78025c8ba6d2d1b76c01e6869a336e8c666e4e0c9a6107715f8abcd0add8bb34:bd387ebc6937b561dfb10e4681bbeff5ac580bd5a85b666f8c7d170d5c298375",
  "india-agra-taj-mahal--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:cda1728ce5dd292551c5c42bf3b1fba2157a44bcf7827c4b9431247e91f30446:fcb431aa74b51fc390174c2aabebd05984fc47483d9ff84454c395736f98bc90",
  "india-agra-taj-mahal--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:ca70335dbc19f4c510147f32393c216b5544a9d0a0167ae7a2a86b62c3bd4586:8f2d2ce7d8a30cda59087388e7f7dd68603ffffbc7d811580766575c6dc68bb9",
  "india-agra-taj-mahal--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:ce2aeafc2a7f699489f57245deae6543d18017e5fb2e8fa97c5d8c90dd61c2c9:d34c3b933f078ac8f0d2f75c11ad122cb0551869d9c1f41b4c47bc5274254c2a",
  "turkey-istanbul-hagia-sophia--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:12bcb5eb6c67ed2123f6eb0dd32c50afd45d039cdf2505ea0afd6c6e6e50bc18:7fd1304510c0178697b36e183cb4e23c1458ed0f7074ea4bbc8247e992dfa4bd",
  "turkey-istanbul-hagia-sophia--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:293069045654cbe058466f0da7782a1f117ec7ba0e00e4df78a49f82fc3f6758:3d953e98f9e59a40124b176a3d524ac13f750bfa766f91c5b883da52fcf174f1",
  "turkey-istanbul-hagia-sophia--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:f513506777b60b124bcf58e3c09b9c99eb5c98506c97a630dc25a3f436e173de:f6cd90a2689f8c102d915194f6c52133242457b93f9f6f33bfe5bc34c08d67e3",
  "brazil-rio-de-janeiro-christ-the-redeemer--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:a79ad30fadb719561480296d2fb3e748d3999dcce9428cdd78cff97778c80154:49cedfc3638ea4c428f2b3f28731104774da4e36e98cdd69d529fc821b90a034",
  "brazil-rio-de-janeiro-christ-the-redeemer--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:dc110ebe2ccff4d4886a2d409eef2aa9060eaa5dec32fb20f3ecba1739f11545:3f63c8206091420c5e84d9c6351bf67c6e793d65b5f710ebe18fd112a6bcc7b2",
  "south-africa-cape-town-table-mountain--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:206475de12d4a490739f09bb5d1c312d31bfc33edd7c9fcaf9172b6cec9e48c3:9e9d4bdeaac0017045dda451efb0ae0e46c8a6d13eb1b4dbd667f5f926b64289",
  "south-africa-cape-town-table-mountain--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:8faee340b3bf3e3789e850a8daf25e571266c8388bbe219b480ac6a540ab35df:c20612573e44acc2d8d509c8e956abb31eea0288acf06c63a5d8dfe6df8e3276",
  "south-africa-cape-town-table-mountain--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:a14d57a0f805a84d1980ec344236b1203f5b5558f6d4ccef5c91c0810d667bce:e13a863a115baf19c2820377bb93ccd8e6290368d06c0316fa44a5d59719eed9",
  "south-africa-cape-town-table-mountain--distant-overlook": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:c32580c005231bc5c5c93dfda9b8c96a8a08e307399bd40b199fe193af567fc6:7b82a231a74f33fd19452dfb5be3c37e695460f51e4d22832164793dc7454449",
  "mexico-yucatan-chichen-itza--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:53ced667bc88c8eb015ca8d26680393796c29880e88604d5fc86d847823f00bc:1c46c2a9cc9cb218d98914ef5671e402de9f9c29d0586e59cdc8c51958ba7002",
  "mexico-yucatan-chichen-itza--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:70c314b39ab394b22ec4e4e7233ca820b58a657106a7a3aef839aadf3450ef51:dacb3602c7a67964ad1146082f23447754e414e5f5f1ad2f8c931167d0a8b3fa",
  "mexico-yucatan-chichen-itza--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:d68d3cd2103395c661205af245a0bd4d38a2dca9236d9ccbfa620fbe7fe5d5cd:2b140614640741cce9d56f1b520307a1ba9ff5070f07739e420a859e51bbcdb0",
  "jordan-petra-al-khazneh--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:6ca21b56e23c752dcc52a655c1c95c904f4bf5edab1deabd0c607ed4df12ca64:66721ae2668ff9387daf5318063f5916e7f9752e9cd5cd9ad20db4f64cdaaa1a",
  "jordan-petra-al-khazneh--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:4b4ae9b682a092bfbbb22fcb49b44e8b4ec55780ad22a3dcb7997c60e0f3b175:91a82981979798d6f9b4d22e0fdf949abe234b1296fdb94d7d09b98586f47a85",
  "cambodia-siem-reap-angkor-wat--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:39f09f4b5cfdc6582ab73fe1da84e24331b14d706ff65c02b6dc468c04728d64:41069c8e7851e22657e7025559d05ceaaae4519f1224864a69521872557a2c8d",
  "cambodia-siem-reap-angkor-wat--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:0ea5e80dc283063a1af0976a1ace078961bfd294c85759db2043657ba03a3b74:c3ae8ad5c34db53ce00bc9fd402d7678db114c94c210a085b67034a747e2fc21",
  "cambodia-siem-reap-angkor-wat--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:31f94a0081aaacb541b6f6db65702c40f8aba53d133bbbdb707df9759feb00e7:aab9c27fe4f859e0885c0d23ea6209fd87d15b086d06376ef02a6b5f49879f49",
  "new-zealand-fiordland-milford-sound--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:15bd7c19291cb670a422feaf5b909b6c91bff25dfbf1b64de86f14c5db3b4796:a037baf2a0d02ee31ab33913cc6aefc41d47c601b7ec17415ebfc76e27ef4e96",
  "new-zealand-fiordland-milford-sound--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:1958c28261d22b6ad4b9ae5bfcadcc7739b5d704cba4502b97e0fa2e60827781:a023ab7434263d933d718d8d238a2d24fb2d63f5890e3b1f7c6750dbe04c130c",
  "new-zealand-fiordland-milford-sound--companion-rare": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:c2cfb56c5f8432be411c7c3da3ef9405e86b0ed27ccb2b906b033c2400ab0f19:cf7db40c9ead6182ebf569769eeafd9f793496fa220a9b985c701abc28c3f260",
  "new-zealand-fiordland-milford-sound--distant-overlook": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:f66cd2db8faa5c1d40773d8e4822d46fe3c02d567f1b4d64e97d4c9fbc2ba124:7c7502da8f777351af8d0123fd05190c1c7ea3ebf4e144b304d720acc07dbf0f",
  "morocco-ouarzazate-ait-benhaddou--day-signature": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:b033052ad70a23918899607c4aef50a7765b538e111519fe190981d94da56635:ea8e174cb30a0f0baf3c515b74b07cfb8a9534c534231d88786739135f304464",
  "morocco-ouarzazate-ait-benhaddou--golden-hour": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:f63a2da2ebf0ef7432b307453f49de3743fcef2c969661098b2fe7b4484aad6d:651a1b6f12abb0e71ce3a634a0dd88fcc17c8e12192cda0f31b0dc03dca8e869",
  "morocco-ouarzazate-ait-benhaddou--distant-overlook": "b6dfe68f17c599d1bb9da5b6c902b27a8975d46831f4e5b7f34be0c9885e9669:ae41d6f60023ed1a2934513217d883a0f6cf7fb992fe230e51f30b22a2e1abee:2824b956a5f003436c63edfbd1f9e397b96fbaac91e8bb99e5a4dded9c2258b5"
} as const

export const DEV_LATEST_ART_MINHO_POSES = {
  "sit": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--sit--watercolor--v02.png",
  "sleep": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--sleep--watercolor--v02.png",
  "walk": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--walk--watercolor--v02.png",
  "eat": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--eat--watercolor--v02.png",
  "play": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--play--watercolor--v02.png",
  "gaze": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--gaze--watercolor--v02.png",
  "sniff": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--sniff--watercolor--v02.png",
  "reach": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--reach--watercolor--v02.png",
  "stretch": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--stretch--watercolor--v02.png",
  "greet": "/dev-art/latest-v5/portraits/minho-watercolor-v2/portrait--minho--greet--watercolor--v02.png"
} as const satisfies Readonly<Record<PortraitPose, string>>
